version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432 
    environment:
      - POSTGRES_PASSWORD=Test123#
      - POSTGRES_USER=test
      - POSTGRES_DB=movies